-- DeveloperOS V1 initial schema
-- Managed by Flyway. Do not edit this migration after it has been applied.
-- Target: PostgreSQL 17 with pgvector

-- The extension may already have been installed by the database administrator.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- The name app_user avoids the PostgreSQL USER keyword.
CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    nickname        VARCHAR(100),
    avatar_url      TEXT,
    bio             VARCHAR(500),
    timezone        VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    preferences     JSONB NOT NULL DEFAULT '{}'::JSONB,
    status          VARCHAR(20) NOT NULL DEFAULT 'active',
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_user_username_not_blank
        CHECK (char_length(btrim(username)) >= 3),
    CONSTRAINT ck_app_user_email_not_blank
        CHECK (char_length(btrim(email)) > 0),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('active', 'disabled', 'locked'))
);

CREATE UNIQUE INDEX uk_app_user_username_lower
    ON app_user ((lower(username)));
CREATE UNIQUE INDEX uk_app_user_email_lower
    ON app_user ((lower(email)));

CREATE TABLE conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    title           VARCHAR(200) NOT NULL DEFAULT 'New conversation',
    model_name      VARCHAR(100),
    status          VARCHAR(20) NOT NULL DEFAULT 'active',
    -- Maintained by MessageService in the same transaction as message creation.
    last_message_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_conversation_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT ck_conversation_title_not_blank
        CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_conversation_status
        CHECK (status IN ('active', 'archived'))
);

CREATE INDEX idx_conversation_user_updated
    ON conversation (user_id, updated_at DESC);
CREATE INDEX idx_conversation_user_status
    ON conversation (user_id, status);

CREATE TABLE message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    content         TEXT NOT NULL DEFAULT '',
    status          VARCHAR(20) NOT NULL DEFAULT 'completed',
    model_name      VARCHAR(100),
    token_count     INTEGER,
    error_message   TEXT,
    metadata        JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE,
    CONSTRAINT ck_message_role
        CHECK (role IN ('system', 'user', 'assistant', 'tool')),
    CONSTRAINT ck_message_status
        CHECK (status IN ('streaming', 'completed', 'failed', 'stopped')),
    CONSTRAINT ck_message_token_count
        CHECK (token_count IS NULL OR token_count >= 0)
);

CREATE INDEX idx_message_conversation_created
    ON message (conversation_id, created_at, id);

CREATE TABLE memory (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    memory_type      VARCHAR(30) NOT NULL,
    content          TEXT NOT NULL,
    source_type      VARCHAR(30) NOT NULL DEFAULT 'manual',
    source_id        BIGINT,
    importance       SMALLINT NOT NULL DEFAULT 3,
    status           VARCHAR(20) NOT NULL DEFAULT 'active',
    last_accessed_at TIMESTAMPTZ,
    metadata         JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memory_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT ck_memory_type
        CHECK (memory_type IN ('goal', 'preference', 'profile', 'project', 'experience', 'event', 'other')),
    CONSTRAINT ck_memory_source_type
        CHECK (source_type IN ('manual', 'conversation', 'growth_log', 'system')),
    CONSTRAINT ck_memory_importance
        CHECK (importance BETWEEN 1 AND 5),
    CONSTRAINT ck_memory_status
        CHECK (status IN ('active', 'archived')),
    CONSTRAINT ck_memory_content_not_blank
        CHECK (char_length(btrim(content)) > 0)
);

CREATE INDEX idx_memory_user_type_status
    ON memory (user_id, memory_type, status);
CREATE INDEX idx_memory_user_updated
    ON memory (user_id, updated_at DESC);

CREATE TABLE knowledge_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    title           VARCHAR(255) NOT NULL,
    original_name   VARCHAR(255) NOT NULL,
    storage_key     VARCHAR(500) NOT NULL,
    mime_type       VARCHAR(150),
    file_size       BIGINT NOT NULL,
    checksum_sha256 CHAR(64),
    status          VARCHAR(20) NOT NULL DEFAULT 'pending',
    chunk_count     INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT,
    metadata        JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_document_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_knowledge_document_storage_key
        UNIQUE (storage_key),
    CONSTRAINT ck_knowledge_document_title_not_blank
        CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_knowledge_document_original_name_not_blank
        CHECK (char_length(btrim(original_name)) > 0),
    CONSTRAINT ck_knowledge_document_file_size
        CHECK (file_size >= 0),
    CONSTRAINT ck_knowledge_document_checksum
        CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9A-Fa-f]{64}$'),
    CONSTRAINT ck_knowledge_document_status
        CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
    CONSTRAINT ck_knowledge_document_chunk_count
        CHECK (chunk_count >= 0)
);

CREATE INDEX idx_knowledge_document_user_status
    ON knowledge_document (user_id, status);
CREATE INDEX idx_knowledge_document_user_created
    ON knowledge_document (user_id, created_at DESC);
CREATE INDEX idx_knowledge_document_user_checksum
    ON knowledge_document (user_id, checksum_sha256)
    WHERE checksum_sha256 IS NOT NULL;

CREATE TABLE knowledge_chunk (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT NOT NULL,
    chunk_index     INTEGER NOT NULL,
    content         TEXT NOT NULL,
    token_count     INTEGER,
    embedding       VECTOR,
    embedding_model VARCHAR(100),
    metadata        JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_chunk_document
        FOREIGN KEY (document_id) REFERENCES knowledge_document (id) ON DELETE CASCADE,
    CONSTRAINT uk_knowledge_chunk_document_index
        UNIQUE (document_id, chunk_index),
    CONSTRAINT ck_knowledge_chunk_index
        CHECK (chunk_index >= 0),
    CONSTRAINT ck_knowledge_chunk_content_not_blank
        CHECK (char_length(btrim(content)) > 0),
    CONSTRAINT ck_knowledge_chunk_token_count
        CHECK (token_count IS NULL OR token_count >= 0),
    CONSTRAINT ck_knowledge_chunk_embedding_model
        CHECK (embedding IS NULL OR embedding_model IS NOT NULL)
);

-- No vector index is created yet. VECTOR has no fixed dimension until the
-- embedding model is selected. Add VECTOR(n) and an HNSW index in a later migration.

CREATE TABLE learning_goal (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    title            VARCHAR(200) NOT NULL,
    description      TEXT,
    status           VARCHAR(20) NOT NULL DEFAULT 'active',
    priority         SMALLINT NOT NULL DEFAULT 3,
    progress_percent SMALLINT NOT NULL DEFAULT 0,
    start_date       DATE,
    target_date      DATE,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_learning_goal_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    -- Required as the referenced key for the tenant-safe composite foreign key.
    CONSTRAINT uk_learning_goal_id_user
        UNIQUE (id, user_id),
    CONSTRAINT ck_learning_goal_title_not_blank
        CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_learning_goal_status
        CHECK (status IN ('draft', 'active', 'paused', 'completed', 'cancelled')),
    CONSTRAINT ck_learning_goal_priority
        CHECK (priority BETWEEN 1 AND 5),
    CONSTRAINT ck_learning_goal_progress
        CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_learning_goal_dates
        CHECK (start_date IS NULL OR target_date IS NULL OR target_date >= start_date)
);

CREATE INDEX idx_learning_goal_user_status
    ON learning_goal (user_id, status);
CREATE INDEX idx_learning_goal_user_target_date
    ON learning_goal (user_id, target_date)
    WHERE target_date IS NOT NULL;

CREATE TABLE learning_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id         BIGINT NOT NULL,
    title           VARCHAR(200) NOT NULL,
    description     TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'todo',
    priority        SMALLINT NOT NULL DEFAULT 3,
    scheduled_date  DATE,
    due_at          TIMESTAMPTZ,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    completed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_learning_task_goal
        FOREIGN KEY (goal_id) REFERENCES learning_goal (id) ON DELETE CASCADE,
    CONSTRAINT ck_learning_task_title_not_blank
        CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_learning_task_status
        CHECK (status IN ('todo', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT ck_learning_task_priority
        CHECK (priority BETWEEN 1 AND 5),
    CONSTRAINT ck_learning_task_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX idx_learning_task_goal_status
    ON learning_task (goal_id, status);
CREATE INDEX idx_learning_task_scheduled_date
    ON learning_task (scheduled_date)
    WHERE scheduled_date IS NOT NULL;
CREATE INDEX idx_learning_task_due_at
    ON learning_task (due_at)
    WHERE due_at IS NOT NULL AND status IN ('todo', 'in_progress');

CREATE TABLE growth_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    goal_id          BIGINT,
    log_type         VARCHAR(20) NOT NULL DEFAULT 'daily',
    title            VARCHAR(200) NOT NULL,
    content          TEXT NOT NULL,
    log_date         DATE NOT NULL DEFAULT CURRENT_DATE,
    duration_minutes INTEGER,
    is_ai_generated  BOOLEAN NOT NULL DEFAULT FALSE,
    metadata         JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_growth_log_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_growth_log_goal_user
        FOREIGN KEY (goal_id, user_id) REFERENCES learning_goal (id, user_id)
        ON DELETE SET NULL (goal_id),
    CONSTRAINT ck_growth_log_type
        CHECK (log_type IN ('daily', 'weekly', 'milestone', 'reflection', 'other')),
    CONSTRAINT ck_growth_log_title_not_blank
        CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_growth_log_content_not_blank
        CHECK (char_length(btrim(content)) > 0),
    CONSTRAINT ck_growth_log_duration
        CHECK (duration_minutes IS NULL OR duration_minutes >= 0)
);

CREATE INDEX idx_growth_log_user_date
    ON growth_log (user_id, log_date DESC, id DESC);
CREATE INDEX idx_growth_log_goal
    ON growth_log (goal_id)
    WHERE goal_id IS NOT NULL;

CREATE TRIGGER trg_app_user_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_conversation_updated_at
    BEFORE UPDATE ON conversation
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_message_updated_at
    BEFORE UPDATE ON message
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_memory_updated_at
    BEFORE UPDATE ON memory
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_knowledge_document_updated_at
    BEFORE UPDATE ON knowledge_document
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_knowledge_chunk_updated_at
    BEFORE UPDATE ON knowledge_chunk
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_learning_goal_updated_at
    BEFORE UPDATE ON learning_goal
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_learning_task_updated_at
    BEFORE UPDATE ON learning_task
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_growth_log_updated_at
    BEFORE UPDATE ON growth_log
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
